### ISSUE TITLE
Message format

### ISSUE THREAD

**Issue by erwindeg** [giovibal/vertx-mqtt-broker-mod#8]
Is there a description of the message format of the messages coming of the event bus?
It looks to be something like type, topic, body with a kind of separator.

**Comment by giovibal** [comment]
It's binary (mqtt encoded).
See MQTTSession.handlePublishMessage (line 240 of branch v22): 
```
Buffer msg = encoder.enc(publishMessage);
if(tenant == null)
    tenant = "";
DeliveryOptions opt = new DeliveryOptions().addHeader(TENANT_HEADER, publishTenant);
vertx.eventBus().publish(ADDRESS, msg, opt);
```
